Added support for signing in and authenticating users. Has bug though in accepting passwords with special characters in them.

diff --git a/website/grades b/website/grades
--- a/website/grades
+++ b/website/grades
@@ -10,16 +10,48 @@ echo "</head>"
 
 echo "<body>"
 
-if [ -z "$user" ]
+if [ -z "$user" -o -z "$password" ]
 then
     echo "<h2>Grades</h2>"
     echo "<form action=\"grades\" method=\"GET\" class=\"gradeform\">"
-    echo "Enter your cs account:<br>"
-    echo "<input type=\"text\" name=\"user\"><br>"
+    echo "Sign into your cs account to view your grades.<br><br>"
+    echo "Username:<br>"
+    echo "<input type=\"text\" name=\"user\" value=\"$user\"><br>"
+    echo "Password:<br>"
+    echo "<input type=\"password\" name=\"password\"><br>"
     echo "<input type=\"submit\" value=\"Enter\" class=\"button\">"
     echo "</form>"
 else
-    echo $(./website/calcgrade.sh $user)
+#    echo $(echo -e "$password\n" | sudo -Sk -u $user ./website/calcgrade.sh)
+#    echo $(expect -c "spawn su $user; expect \"Password: \"; send \"$password\n\"")
+#    ./website/getgrade.exp
+    var=$(./website/authuser.exp $user $password)
+    echo "var is $var" >&2
+   if [ "$var" == "incorrect" ]; then
+        echo "<h2>Grades</h2>"
+        echo "<p class=\"error\"><b>Invalid user name and/or password.</b></p>"
+        echo "<form action=\"grades\" method=\"GET\" class=\"gradeform\">"
+        echo "Sign into your cs account to view your grades.<br><br>"
+        echo "Username:<br>"
+        echo "<input type=\"text\" name=\"user\" value=\"$user\"><br>"
+        echo "Password:<br>"
+        echo "<input type=\"password\" name=\"password\"><br>"
+        echo "<input type=\"submit\" value=\"Enter\" class=\"button\">"
+        echo "</form>"
+    elif [ "$var" == "correct" ]; then
+        ./website/calcgrade.sh $user
+    else
+        echo "<h2>Grades</h2>"
+        echo "<p class=\"error\"><b>Error signing in. Please try again.</b></p>"
+        echo "<form action=\"grades\" method=\"GET\" class=\"gradeform\">"
+        echo "Sign into your cs account to view your grades.<br><br>"
+        echo "Username:<br>"
+        echo "<input type=\"text\" name=\"user\" value=\"$user\"><br>"
+        echo "Password:<br>"
+        echo "<input type=\"password\" name=\"password\"><br>"
+        echo "<input type=\"submit\" value=\"Enter\" class=\"button\">"
+        echo "</form>"
+    fi
 fi
 
 echo "<br><br>"
